version: '3.9'
services:
  db:
    image: "mysql:8.0.29"
    environment:
      - MYSQL_ROOT_PASSWORD=1023
    ports:
      - "3306:3306"
  web:
    build: ,
    depends_on:
      - db
    links:
      - "db:dptodoappserver"
